name: Python libraries

on:
  push:

jobs:
  logging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/poetry-buildpack@main
        with:
          working-directory: py
          test-entry-point: pytest
          tests: py/tests
        env:
          NEW_RELIC_LICENSE_KEY: ${{secrets.NEW_RELIC_LICENSE_KEY}}
          LOGDNA_INGESTION_KEY: ${{secrets.LOGDNA_INGESTION_KEY}}
          LOGTAIL_TOKEN: ${{secrets.LOGTAIL_TOKEN}}
          LOGTAIL_HOST: ${{vars.LOGTAIL_HOST}}